# Generated by Django 4.1.1 on 2022-09-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('release_year', models.IntegerField(null=True)),
                ('country', models.CharField(max_length=50)),
                ('duration', models.FloatField(max_length=10, null=0)),
                ('rating', models.FloatField(max_length=5, null=0)),
                ('description', models.CharField(default='', max_length=5000)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(related_name='films', to='kinozal.actor')),
                ('categories', models.ManyToManyField(related_name='films', to='kinozal.category')),
                ('directors', models.ManyToManyField(related_name='films', to='kinozal.director')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kinozal.film')),
            ],
        ),
    ]
