# Generated by Django 4.1.1 on 2022-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0003_alter_film_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
