# Generated by Django 4.1.1 on 2022-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='base_url',
            field=models.URLField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
