# Generated by Django 4.1.1 on 2022-10-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0006_alter_comment_films'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
