# Generated by Django 4.1.1 on 2022-10-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0007_alter_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='country',
            field=models.ManyToManyField(related_name='films', to='kinozal.country'),
        ),
    ]
