# Generated by Django 4.1.1 on 2022-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0008_country_remove_film_country_film_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='base_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
