# Generated by Django 4.1.1 on 2022-10-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0011_film_description_en_film_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='director',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
    ]
