# Generated by Django 4.1.1 on 2022-10-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0012_actor_name_en_category_name_en_director_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='duration_en',
            field=models.CharField(default='', max_length=50),
        ),
    ]
