# Generated by Django 4.1.1 on 2022-12-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0013_film_duration_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='duration',
            new_name='views',
        ),
    ]
