# Generated by Django 4.1.1 on 2022-12-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0014_rename_duration_film_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='duration_en',
            new_name='views_en',
        ),
    ]
