# Generated by Django 4.1.1 on 2022-12-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinozal', '0016_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
